# Generated by Django 3.0.2 on 2020-02-28 13:34

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_category', models.CharField(default='その他', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmallCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_category', models.CharField(default='その他', max_length=20)),
                ('big_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BigCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('paid_at', models.DateTimeField()),
                ('big_category', models.ForeignKey(default=app.models.set_big_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.BigCategory')),
                ('small_category', models.ForeignKey(default=app.models.set_small_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.SmallCategory')),
            ],
        ),
    ]
