# Generated by Django 3.0.3 on 2020-05-17 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BigCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_category', models.CharField(default='その他', max_length=20, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmallCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_category', models.CharField(default='その他', max_length=20)),
                ('big_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BigCategory')),
            ],
            options={
                'unique_together': {('small_category', 'big_category')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('paid_at', models.DateField(default=django.utils.timezone.now)),
                ('small_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.SmallCategory')),
            ],
        ),
    ]
